# Workaround until we have https://pagure.io/koji/pull-request/2151

- name: update koji-gc for GSSAPI
  get_url:
    url: https://pagure.io/fork/tkopecek/koji/raw/issue2143/f/util/koji-gc
    dest: /usr/sbin/koji-gc
    owner: root
    group: root
    mode: 0755

- name: use python3 for /usr/sbin/koji-gc
  lineinfile:
    dest: /usr/sbin/koji-gc
    regexp: '^#!/usr/bin/python2'
    line: "#!/usr/bin/python3"
  when: ansible_distribution_file_variety == "RedHat" and ansible_distribution_major_version|int > 7
