# Workaround until we have https://pagure.io/koji/pull-request/2151

- name: update koji-gc for GSSAPI
  get_url:
    url: https://pagure.io/fork/tkopecek/koji/raw/issue2143/f/util/koji-gc
    dest: /usr/sbin/koji-gc
    owner: root
    group: root
    mode: 0755
