- name: Install Kerberos packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - krb5-server
    - krb5-workstation

- name: copy /etc/krb5.conf
  copy:
    src: files/krb5.conf
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644

- name: copy /var/kerberos/krb5kdc/kdc.conf
  copy:
    src: files/kdc.conf
    dest: /var/kerberos/krb5kdc/kdc.conf
    owner: root
    group: root
    mode: 0600

- name: configure /var/kerberos/krb5kdc/kadm5.acl
  copy:
    dest: /var/kerberos/krb5kdc/kadm5.acl
    owner: root
    group: root
    mode: 0600
    content: |
      */admin@KOJIDEV.EXAMPLE.COM	*

- name: initialize KDC DB
  command: /usr/sbin/kdb5_util create -s -P test
  args:
    creates: /var/kerberos/krb5kdc/principal.ok

#- name: restart krb5kdc
#  service:
#    name: krb5kdc
#    enabled: yes
#    state: restarted
#
#- name: restart kadmin
#  service:
#    name: kadmin
#    enabled: yes
#    state: restarted

- name: create krb principal
  include: principal.yml principal={{ item }}
  with_items:
    - kdreyer/admin
    - kdreyer
    - rcm/debbuild
    - HTTP/kojidev.example.com
    - compile/kojidev.example.com
