- name: check if {{ principal }} account exists
  command: /usr/sbin/kadmin.local -q "getprinc {{ principal }}"
  check_mode: no
  register: account_exists
  tags:
   - krb_account

- name: create {{ principal }} account
  command: /usr/sbin/kadmin.local -q "addprinc -randkey {{ principal }}"
  when: account_exists.stderr is search("Principal does not exist")
  tags:
   - krb_account

- name: "determine {{ principal }} keytab file name"
  set_fact:
    keytab: "/var/local/{{ principal | replace ('/', '.') }}.keytab"
  tags:
   - krb_account

- name: create {{ keytab }}
  command: /usr/sbin/kadmin.local -q "ktadd -k {{ keytab }} {{ principal }}"
  args:
    creates: "{{ keytab }}"
  tags:
   - krb_account
