- name: install prerequisites
  package:
    name:
    - git-core
    - python3
    state: present

- name: install el7 prerequisites
  package:
    name:
    - python36-cryptography
    - python36-dateutil
    state: present
  when: ansible_distribution_file_variety == "RedHat" and ansible_distribution_major_version|int == 7

- name: clone koji-tools.git
  git:
    repo: https://pagure.io/koji-tools.git
    dest: /usr/local/koji-tools

- name: /etc/pki/koji directory
  file:
    path: /etc/pki/koji
    state: directory
    mode: 0755

- name: Create a Koji SSL CA
  command:
    argv:
    - /usr/local/koji-tools/src/bin/koji-ssl-admin
    - new-ca
    - --common-name
    - Test Koji CA
    creates: /etc/pki/koji/koji-ca.crt
    chdir: /etc/pki/koji/

- name: Create a Server CSR
  command:
    argv:
    - /usr/local/koji-tools/src/bin/koji-ssl-admin
    - server-csr
    - kojidev.example.com
    creates: /etc/pki/koji/kojidev.example.com.csr
    chdir: /etc/pki/koji/

- name: Sign Server CSR
  command:
    argv:
    - /usr/local/koji-tools/src/bin/koji-ssl-admin
    - sign
    - kojidev.example.com.csr
    creates: /etc/pki/koji/kojidev.example.com.chain.crt
    chdir: /etc/pki/koji/
