- name: Install Koji builder packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - koji-builder

- name: copy /etc/kojid/kojid.conf
  copy:
    src: files/kojid.conf
    dest: /etc/kojid/kojid.conf
    owner: root
    group: root
    mode: 0644

- name: restart kojid
  service:
    name: kojid
    enabled: true
    state: started
